config/routes.rb
Rails.application.routes.draw do
  
  resources :notes do 
      resources :reviews
  end  
  resources :topics
  resources :subtopics
  resources :answers
  resources :questions
  resources :users, except: [:new]

  
  
   root 'welcome#home'
   get 'welcome/ingresar_preguntas', to: 'welcome#ingresar_preguntas'
   get 'welcome/ver_preguntas', to: 'welcome#ver_preguntas'

   post '/add_question' => 'welcome#ingresar_preguntas'

  get 'signup', to: 'users#new' 
  get 'login', to: 'sessions#new' 
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  get 'courses', to: 'notes#cursos'

end

app/models/note.rb
class Note < ActiveRecord::Base


		mount_uploader :portada, PortadaUploader 
		#relations
		has_many :topics , dependent: :destroy
		has_many :reviews

end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
  before_action :set_note, only: [:show, :edit, :update, :destroy]

  # GET /notes
  # GET /notes.json
  def index
    @notes = Note.all
  end

  # GET /notes/1
  # GET /notes/1.json
  def show
    @reviews = Review.where(note_id: @note.id)
  end

  # GET /notes/new
  def new
    @note = Note.new
  end

  # GET /notes/1/edit
  def edit
  end

# GET /notes/1/edit
  def cursos
    @notes = Note.where(published: true)
  end



  # POST /notes
  # POST /notes.json
  def create
    @note = Note.new(note_params)

    respond_to do |format|
      if @note.save
        format.html { redirect_to @note, notice: 'Note was successfully created.' }
        format.json { render :show, status: :created, location: @note }
      else
        format.html { render :new }
        format.json { render json: @note.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /notes/1
  # PATCH/PUT /notes/1.json
  def update
    respond_to do |format|
      if @note.update(note_params)
        format.html { redirect_to @note, notice: 'Note was successfully updated.' }
        format.json { render :show, status: :ok, location: @note }
      else
        format.html { render :edit }
        format.json { render json: @note.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /notes/1
  # DELETE /notes/1.json
  def destroy
    @note.destroy
    respond_to do |format|
      format.html { redirect_to notes_url, notice: 'Note was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_note
      @note = Note.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def note_params
      params.require(:note).permit(:name, :is_pay, :price, :teacher, :description, :is_video, :preview, :published, :portada)
    end
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/views/notes/_form.html.erb
<%= form_for(@note, :html => {multipart: true}) do |f| %>
  <% if @note.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@note.errors.count, "error") %> prohibited this note from being saved:</h2>

      <ul>
      <% @note.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :is_pay %><br>
    <%= f.check_box :is_pay %>
  </div>
  <div class="field">
    <%= f.label :price %><br>
    <%= f.number_field :price %>
  </div>
  <div class="field">
    <%= f.label :teacher %><br>
    <%= f.text_field :teacher %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </div>
  <div class="field">
    <%= f.label :is_video %><br>
    <%= f.check_box :is_video %>
  </div>
  <div class="field">
    <%= f.label :Imagen %><br>
    <%= f.file_field :portada %>
  </div>
  <div class="field">
    <%= f.label :published %><br>
    <%= f.check_box :published %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/notes/cursos.html.erb
<div class="container">
	<div class="col-md-12 text-center bold-whitney tittle-backline-black">
		<h1>¿Qué quieres Estudiar?</h1>
		<hr>
	</div>
</div>

<br>
<br>
<br>

<div class="container" id="appuntes-container">
	<% @notes.each do |note| %>
		<div class="col-md-3">
		<%= link_to(note, class: "thumbnail")  do %>
			<span class="caption normal-whitney">
				<%= image_tag note.portada.url, class: "img-responsive" %>
				<span class="note-name"><%= note.name.downcase  %></span>
				<span class="light-close">Por <%= note.teacher %></span>
				
			 </span>
			<% end %>
		<% end %>
		</div>			
</div>

app/views/notes/edit.html.erb
<h1>Editing Note</h1>

<%= render 'form' %>

<%= link_to 'Show', @note %> |
<%= link_to 'Back', notes_path %>

app/views/notes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Notes</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Is pay</th>
      <th>Price</th>
      <th>Teacher</th>
      <th>Description</th>
      <th>Is video</th>
      <th>Preview</th>
      <th>Published</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @notes.each do |note| %>
      <tr>
        <td><%= note.name %></td>
        <td><%= note.is_pay %></td>
        <td><%= note.price %></td>
        <td><%= note.teacher %></td>
        <td><%= note.description %></td>
        <td><%= note.is_video %></td>
        <td><%= note.preview %></td>
        <td><%= note.published %></td>
        <td><%= link_to 'Show', note %></td>
        <td><%= link_to 'Edit', edit_note_path(note) %></td>
        <td><%= link_to 'Destroy', note, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Note', new_note_path %>

app/views/notes/new.html.erb
<h1>New Note</h1>

<%= render 'form' %>

<%= link_to 'Back', notes_path %>

app/views/notes/show.html.erb
<div class="col-md-12 text-center bold-whitney tittle-backline-black">
		<h2 align="center"> Contenido: </h2><br>
		<hr>
	</div>


<div class="row">
	<div class="col-md-6">
				
				<%= @note.name  %><br>
				<% @note.topics.each do |topic| %>
					-<%= topic.name %><br>
					<% topic.subtopics.each do |subtopic| %>
						------<%= subtopic.name %><br>
							<% subtopic.questions.each do |question| %>
								----------<%= question.content %><br>
								----------<%= question.answer.content if question.answer %><br>
								
							<% end %>
					<% end %>
				<% end %>
	</div>


	<div class="col-md-6">

		 <h4> Comenta: </h4><br>
		<%= link_to "Escribe una Reseña", new_note_review_path(@note), class: "btn btn-link" %>
		<% @reviews.each do |review| %>

				<div class="star-rating" data-score= <%= review.rating %>s></div>
				<p><%= review.comment %></p>

		<% end %>
	
</div>	
</div>
</div>	

<script>
$('.star-rating').raty({
	path: 'https://s3.amazonaws.com/fotospipe/stars',
	readOnly: true,
	score: function() {
		return $(this).attr('data-score');
	}
});
</script>