config/routes.rb
Rails.application.routes.draw do
  
  resources :notes do 
      resources :reviews
  end  
  resources :topics
  resources :subtopics
  resources :answers
  resources :questions
  resources :users, except: [:new]

  
  
   root 'welcome#home'
   get 'welcome/ingresar_preguntas', to: 'welcome#ingresar_preguntas'
   get 'welcome/ver_preguntas', to: 'welcome#ver_preguntas'

   post '/add_question' => 'welcome#ingresar_preguntas'

  get 'signup', to: 'users#new' 
  get 'login', to: 'sessions#new' 
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  get 'courses', to: 'notes#cursos'

end

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/"><strong>App</strong>unte</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">

      <% if logged_in? %>
      <li> <%= link_to 'Ingresar Preguntas', welcome_ingresar_preguntas_path %></a>  </li>
      
      <li><%= link_to 'Ver Preguntas', welcome_ver_preguntas_path %></a></li>
      <% end %>
      
      </ul>



      <form class="navbar-form navbar-left">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search">
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
      </form>
      <ul class="nav navbar-nav navbar-right">
          <% if logged_in? %>

          <li><a href="#">Mis Cursos</a></li>

  
         
         
         

          <li class="dropdown">
          
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
            <img src="<%= current_user.avatar.url %>" alt=""> 
            Mi Perfil <span class="caret"></span>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "Editar Perfil", edit_user_path(current_user) %></li>
              <li><%= link_to "Mi Perfil", user_path(current_user) %></li>
              <li><a href="#">Something else here</a></li>
              <li role="separator" class="divider"></li>
              <li><%= link_to 'Log out', logout_path, method: :delete %>   </li>
            </ul>
          </li>
        
          <% else %>
          <li><%= link_to 'Log in', login_path  %></li>
          <li><%= link_to 'Sign in', signup_path  %></li>
          <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Udemy</title>
   <link href="http://netdna.bootstrapcdn.com/bootstrap/3.0.0/css/bootstrap.min.css" rel="stylesheet">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <!-- <meta name="viewport" content="width=device-width, initial-scale=1.0"> -->

    <!-- Bootstrap -->



 

</head>
<body>

  <%= render 'layouts/navigation' %>
 
 	<div class="container-fluid">
		
		<%= yield %>
    <%= debug(params) if Rails.env.development? %>
	</div>

</body>
</html>